packages:
  - packages/*
  - packages/temporal-adapter/*
  - platform/*
  - platform/apps/*
  - platform/foundation/*
  - platform/modules/*
  - platform/workers/*
  - showcase/*
enableGlobalVirtualStore: false
allowBuilds:
  '@swc/core': false
  esbuild: false
  protobufjs: false
